### ISSUE TITLE
  Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/Genoplan/Documents/GitHub/services/node_modules/get-intrinsic/package.json

### ISSUE THREAD

**Issue by softmarshmallow** [Butterwire/serverless-plugin-monorepo#22] opened 2020-11-06 09:24 UTC
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/Genoplan/Documents/GitHub/services/node_modules/get-intrinsic/package.json

**Comment by tysoncadenhead** [comment] 2020-11-19 15:03
This appears to be the fix: https://github.com/Butterwire/serverless-plugin-monorepo/pull/23
At least, it works on my side.

**Comment by martin-css** [comment] 2020-11-20 11:20
Duplicate of #21, fixed in v0.10.0.

**Closed by martin-css** 2020-11-20 11:20 UTC
